version: '3.8'

services:
  app:
    container_name: raindrop-app
    image: raindrop-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      # 호스트의 application.yml.example을 컨테이너의 application.yml로 마운트
      - ./src/main/resources/application.yml.example:/app/src/main/resources/application.yml
