version: '3.8'

services:
  app:
    container_name: raindrop-app
    image: raindrop-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://awseb-e-ecg3kypfda-stack-awsebrdsdatabase-zuhgc1zbkxb6.crg688g4kko4.ap-northeast-2.rds.amazonaws.com:3306/raindrop
      - SPRING_DATASOURCE_USERNAME=raindrop
      - SPRING_DATASOURCE_PASSWORD=raindropeureka
    volumes:
      # 호스트의 application.yml.example을 컨테이너의 application.yml로 마운트
      - ./src/main/resources/application.yml.example:/app/src/main/resources/application.yml
