spring:
  application:
    name: raindrop
  datasource:
    url: jdbc:mysql://localhost:3306/raindrop
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  sql:
    init:
      mode: always
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE
    com:
      example:
        demo: DEBUG

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.example.demo
  mapper-locations: classpath:mappers/**/*.xml

kakao:
  client-id: 8162b95c200bcd82ce88d8c5468f41c5
  redirect-uri: http://localhost:5173/auth/login/kakao

jasypt:
  encryptor:
    password: parkhani_raindrop_8f2xA7pLzQ!
    algorithm: PBEWithMD5AndDES